### This notes are from Coursera Learning R from JHU

## Most foundamental things

In [6]:
# source的意思是引用这个.r文件里面的函数
source("C:/Users/handsomevictor/Desktop/学习R/working directory/coursera11.R")
ls() #看都有哪些函数
second(3:10)

[1] "myfunction"   "second"       "var_dic_list"

[1]  2.255334  3.270319  4.947548  5.752870  6.983405  8.213364 10.317381
[8]  9.926451

In [10]:
# 赋值
x <- 1
x

msg <- 'I love you'
msg # it's auto-printing
print(msg) # this is explicit printing

[1] 1

[1] "I love you"

[1] "I love you"


In [21]:
x <- 1:20
x
y <- 10:1
y

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[1] 10  9  8  7  6  5  4  3  2  1

R has basic classes:<br>
character; numeric, integer, complex, logical (bool)<br>
the most important object is vector which can be created by vector()<br>
get the attribute of an object by attribute()

In [28]:
# creating objects
x <- c(0.5, 0.6)
x
x <- c(TRUE, FALSE)
x
x <- c(T, F) # a simplified way of bool
x
x <- c('a', 'b', 'c')
x
x <- c(1+10i, 1+3i) # complex number
x

[1] 0.5 0.6

[1]  TRUE FALSE

[1]  TRUE FALSE

[1] "a" "b" "c"

[1] 1+10i 1+ 3i

In [29]:
x <- c(0.5, 'a', TRUE)  # it can be a combination
x
# in R, TRUE stands for 1, FALSE for 0

[1] "0.5"  "a"    "TRUE"

In [37]:
# use class(x)
y <- 10:0
class(y)

# it's easy to change the object into different types 更改数值类型
as.numeric(y)
as.logical(y)
as.character(y)
as.complex(y)

[1] "integer"

[1] 10  9  8  7  6  5  4  3  2  1  0

[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE

[1] "10" "9"  "8"  "7"  "6"  "5"  "4"  "3"  "2"  "1"  "0"

[1] 10+0i  9+0i  8+0i  7+0i  6+0i  5+0i  4+0i  3+0i  2+0i  1+0i  0+0i

In [44]:
# Lists
x <- list(1, 'a', 1+5i, TRUE)
# 直接单括号是返回index加数值
x[1]
# 双括号是只返回数值
x[[4]]

# 这里第一个并不是从0开始！

[[1]]
[1] 1

[1] TRUE

In [50]:
# 矩阵
m <- matrix(nrow=2, ncol=3)
m
dim(m)
attributes(m)

m <- matrix(1:6, nrow=2, ncol=3) # 会自动判定1*6是否等于2*3
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

[1] 2 3

$dim
[1] 2 3

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [58]:
# 矩阵
m <- 1:10
dim(m) <- c(2, 5)  # 通过numeric的c来创建matrix
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [60]:
# 矩阵
x <- 1:3
y <- 10:12
cbind(x, y) # colume binding 把输入的值当作colume
rbind(x, y) # row binding

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

In [71]:
# Factors 因子类型
x <- factor(c('yes', 'no', 'yes', 'yes'))
x
table(x) # 直接有一个简单的统计
unclass(x)

[1] yes no  yes yes
Levels: no yes

x
 no yes 
  1   3 

[1] 2 1 2 2
attr(,"levels")
[1] "no"  "yes"

In [70]:
# factor，改变输出顺序
x <- factor(c('yes', 'no', 'yes', 'yes'),
           levels = c('yes', 'no'))
x

[1] yes no  yes yes
Levels: yes no

In [85]:
# missing values
# NaN is considered as NA but the converse is wrong
x <- c(1, 3, NA, NaN)
x
is.na(x)
is.nan(x)

[1]   1   3  NA NaN

[1] FALSE FALSE  TRUE  TRUE

[1] FALSE FALSE FALSE  TRUE

In [89]:
# Data Frams
x <-data.frame(foo = 1:4, bar = c(T,T,F,F)) # 括号里面的是dataframe里面的内容！
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [91]:
# names
x <- 1:3
names(x)
names(x) <- c('foo', 'bar', 'norf')
x
# 相当于list中每个单位都有了自己的名字

NULL

foo  bar norf 
   1    2    3

In [92]:
# names
# list也可以有名字
m <- list(a=12, b=23)
m
names(m)

$a
[1] 12

$b
[1] 23

[1] "a" "b"

In [97]:
# names
# 矩阵也可以有名字
m <- matrix(1:4, nrow=2, ncol=2)
m
dimnames(m) = list(c('a', 'b'), c('c', 'd'))
m

names(m) # 因为设置的是dimnames所以names里面为空
dimnames(m) # 为设置里面的list内容

[,1] [,2]
[1,] 1    3   
[2,] 2    4

c d
a 1 3
b 2 4

NULL

[[1]]
[1] "a" "b"

[[2]]
[1] "c" "d"

In [116]:
# reading data 读取数据
# read.table, read.csv是读取外部tabular数据
# readLines读取一个txt文件每一行
# source读取外部R code
# dget读取外部R code (inverse of dput)
# load读取in saved workspaces
# unserialize读取single R objects in binary form

# 注意：外部数据地址的/一定不是\!
# read.table()会自动识别txt和csv! read.csv()仅有的不同为the seperator is a comma
direction = 'C:/Users/handsomevictor/Desktop/学习R/try.csv'
text_direction = 'C:/Users/handsomevictor/Desktop/学习R/hate you.txt'

data = read.csv(direction)
data

text_file = read.table(text_direction)
text_file # txt文件按每一行输出dataframe格式!

name grade     height
1 a    83.661087 1     
2 s    74.432939 2     
3 v    66.755592 3     
4 w     3.813707 4     
5 f    55.148212 5     
6 d    63.216028 6     
7 x    56.852869 7     
8 ws   33.555481 8     
9 f    85.509272 9

V1           
1  sdouiwooiuwxe
2  pwex         
3  pweup        
4  9xuwep9w     
5  pwue9p       
6  xwe9p        
7  xnwepu9      
8  rnupwe9      
9  nusp         
10 9nfpsomfosmo;

In [128]:
# reading large tables
# 读取大量数据
# 如果内存不够用，先尝试comment.char = "" if there are no commenred lines in your file
# 也可以用colClasses来让R运行的更快

initial <- read.table('C:/Users/handsomevictor/Desktop/学习R/hate you.txt', nrows = 3) # 这里nrows指的是前多少行，不会让R更快，但会让内存更好
initial

classes <- sapply(initial, class) # 这个只是获取initial里面的每一列的种类，好让r运行的更快点
tabAll <- read.table('C:/Users/handsomevictor/Desktop/学习R/hate you.txt',
                    colClasses = classes, nrows = 5) # 这种办法更快
tabAll

V1           
1 sdouiwooiuwxe
2 pwex         
3 pweup

V1           
1 sdouiwooiuwxe
2 pwex         
3 pweup        
4 9xuwep9w     
5 pwue9p

In [132]:
# dput-ting R object
y <- data.frame(a=1, b='a')
y
dput(y) # 可以看到具体信息，根据这些信息足够创建一个y了，reconstruct R object
dput(y, file='y.R')
new.y <- dget('y.R') # 会产生一个y.R的文件，供短期使用
new.y

a b
1 1 a

structure(list(a = 1, b = "a"), class = "data.frame", row.names = c(NA, 
-1L))


a b
1 1 a

In [137]:
# dumping
x <- 'foo'
y <- data.frame(a=1, b='a')
dump(c('x', 'y'), file='data.R')
y
rm(x, y)
# y # 此时已经被remove掉了

source('data.R')
y

a b
1 1 a

a b
1 1 a

In [141]:
# interface to the outside world
# file, gzfile (compressed with gzip), bzfile, url
str(file)
str(gzfile) # 查看细节，没啥用

function (description = "", open = "", blocking = TRUE, encoding = getOption("encoding"), 
    raw = FALSE, method = getOption("url.method", "default"))  
function (description, open = "", encoding = getOption("encoding"), compression = 6)  


In [148]:
# connections
con <- file('C:/Users/handsomevictor/Desktop/学习R/hate you.txt', 'r')
data <- read.csv(con)
close(con)
con
# 这个跟data <- read.csv(direction)一样

A connection with                            
description "rval"          
class       "textConnection"
mode        "w"             
text        "text"          
opened      "opened"        
can read    "no"            
can write   "yes"           

In [153]:
# 也可以用readLines来读取网页
con <- url('http://zhenning-li.com/', 'r')
x <- readLines(con)
head(x) # 爬取的是html

[[1]]
[1] "<!DOCTYPE html>"                                                         
[2] "<html lang=\"en-US\">"                                                   
[3] "<head>"                                                                  
[4] "<meta charset=\"UTF-8\">"                                                
[5] "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
[6] "<link rel=\"profile\" href=\"https://gmpg.org/xfn/11\">"

In [161]:
# subsetting R objects
# [] returns an object of the same class as the original
# [[]] is used to extract elements of a list or a data frame, used to extract a single element
# $ us used for returning certain names
x <- c(1, 2, 3, 4, 5, 4, 4, 3, 2)
x[1]
class(x[1])

x[1:4]
class(x[1:4])

x[[1]]
class(x[[1]])

[1] 1

[1] "numeric"

[1] 1 2 3 4

[1] "numeric"

[1] 1

[1] "numeric"

In [167]:
# subsetting R objects
x <- c('a','b','c','d','e',3)
x[1]
x[x > 'a'] # 这里字母可以比较大小! 但是不会返回数字

u<- x>'a'
u
x[u]

[1] "a"

[1] "b" "c" "d" "e"

[1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE

[1] "b" "c" "d" "e"

In [180]:
# subsetting R lists
x <- list(foo=1:4, bar=0.6)
x
'-------'
x[2]
x[1]
class(x[1]) # 这个是list! 跟原来的class一样

x[[1]]
class(x[[1]]) # 这个返回是sequence，改变了class!

'-------'
x$bar # class是sequence的numeric
x[['bar']] # class是sequence的numeric
x['bar'] # class是list

$foo
[1] 1 2 3 4

$bar
[1] 0.6

[1] "-------"

$bar
[1] 0.6

$foo
[1] 1 2 3 4

[1] "list"

[1] 1 2 3 4

[1] "integer"

[1] "-------"

[1] 0.6

[1] 0.6

$bar
[1] 0.6

In [183]:
x <- list(foo=1:4, bar=0.6, chinese='hello')
x[c(1,3)] # 只返回第一第三个list的element

$foo
[1] 1 2 3 4

$chinese
[1] "hello"

In [196]:
x <- list(a=list(1, 2, 3), b=c(4, 5))
x[[1]]
x[[1]][3]
x[[1]][[3]]

x[[c(1, 2)]] # 这个表示的是，list中第一个element中的第二项!!!!

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[1]]
[1] 3

[1] 3

[1] 2

In [201]:
# subsetting matrices
x <- matrix(1:6, 2, 3)
x
x[1, 2] # 第一行第二列!
x[2, 1]
class(x[2, 1]) # 返回的就是一个数

x[1, 2, drop=FALSE]
class(x[1, 2, drop=FALSE]) # 这个返回的是1*1的matrix，以防以后出现问题

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 3

[1] 2

[1] "integer"

[,1]
[1,] 3

[1] "matrix" "array"

In [204]:
# subsetting matrices
x <- matrix(1:6, 2, 3)
x[1,] # 返回第一列，class是sequence integer
class(x[1,])
x[1, , drop=FALSE]
class(x[1, , drop=FALSE])

[1] 1 3 5

[1] "integer"

[,1] [,2] [,3]
[1,] 1    3    5

[1] "matrix" "array"

In [211]:
# subsetting with names, partial matching 用部分name来做匹配!
x <- list(aa=1:5)
x
'----------------------------------------------------'
x$a # looks for a name in the list that matches 'a'
x[['a']] # 这个返回null是因为R自动判断需要有一个完全等于'a'，但并不存在
x[['a', exact=FALSE]]

$aa
[1] 1 2 3 4 5

[1] "----------------------------------------------------"

[1] 1 2 3 4 5

NULL

[1] 1 2 3 4 5

In [215]:
# removing missing values
x <- c(NA, NaN, 1, 2, 3)
bad <- is.na(x)
bad
!bad # 取反
x[!bad] # 这样就可以直接移除了!

[1]  TRUE  TRUE FALSE FALSE FALSE

[1] FALSE FALSE  TRUE  TRUE  TRUE

[1] 1 2 3

In [222]:
# removing missing values
# 如果有多种格式的数据
# complete.cases() 可以去除data frame中的NA行，方便后续对文本的分析和处理

x <- c(NA, NaN, 1, 2, 'hello')
y <- c('a', 'b', NA, NA, 1)
good <- complete.cases(x, y)
good # 去掉了NA行，所以只剩下2和5是TRUE了
good_x <- complete.cases(x) # 去掉处于位置1的NA
good_x

x[good_x]
y[good]

[1] FALSE  TRUE FALSE FALSE  TRUE

[1] FALSE  TRUE  TRUE  TRUE  TRUE

[1] "NaN"   "1"     "2"     "hello"

[1] "b" "1"

In [233]:
# removing missing values
# 在dataframe里面使用complete.cases()

direction = 'C:/Users/handsomevictor/Desktop/学习R/try.csv'
data = read.csv(direction)
head(data)
data[1:3, 1:2] #slicing

# 替换几个数，可以直接赋值
data[1, 3] = NA
data[5, 2] = NA
data

good <- complete.cases(data) # 此时good是按每一行来判断是否有NA的
data[good, ][1:3, ] # !!!!!!!!!!!!!!后面这两个逗号一定要加!因为good本质上是sequence bool，而data是dataframe需要两个参数，所以第二个得有

name grade     height
1 a    83.661087 1     
2 s    74.432939 2     
3 v    66.755592 3     
4 w     3.813707 4     
5 f    55.148212 5     
6 d    63.216028 6

name grade   
1 a    83.66109
2 s    74.43294
3 v    66.75559

name grade     height
1 a    83.661087 NA    
2 s    74.432939  2    
3 v    66.755592  3    
4 w     3.813707  4    
5 f           NA  5    
6 d    63.216028  6    
7 x    56.852869  7    
8 ws   33.555481  8    
9 f    85.509272  9

name grade     height
2 s    74.432939 2     
3 v    66.755592 3     
4 w     3.813707 4

In [237]:
# vectorized operation
# things can happen in paralled
x <- 1:4; y <- 2:5 # 本质上x是一个有4个数据的向量
x + y
x > 2
y == 5
x * y
x / y

[1] 3 5 7 9

[1] FALSE FALSE  TRUE  TRUE

[1] FALSE FALSE FALSE  TRUE

[1]  2  6 12 20

[1] 0.5000000 0.6666667 0.7500000 0.8000000

In [240]:
# vectorized matrix operation
x <- matrix(1:4, 2, 2); y <- matrix(rep(10, 4), 2, 2) # 这里rep指的是重复值! 复制!
y
x * y
x / y

# 矩阵乘积 %*%
x %*% y

[,1] [,2]
[1,] 10   10  
[2,] 10   10

[,1] [,2]
[1,] 10   30  
[2,] 20   40

[,1] [,2]
[1,] 0.1  0.3 
[2,] 0.2  0.4

[,1] [,2]
[1,] 40   40  
[2,] 60   60

In [299]:
# 不同长度的vector也是可以相加的!
x <- 1:4
y <- 2:3
z <- 9
x
y
x+y
x+z # 只有一个数字作为sequence的话，是其他vector每一项都加上他!
class(x+y)

[1] 1 2 3 4

[1] 2 3

[1] 3 5 5 7

[1] 10 11 12 13

[1] "integer"

In [253]:
# 把vector的数改掉有两种办法
x <- c(17, 14, 4, 5, 13, 12, 10)
x[x>10] <- 999
x
x[x>10] = 99999
x

[1] 999 999   4   5 999 999  10

[1] 99999 99999     4     5 99999 99999    10

In [ ]:
# 'matrix', 'table', 'data frame', 'array' are not atomic data type in R

### Quiz1里面practice中用到的技巧

In [291]:
# 做quiz用到的
direction = 'C:/Users/handsomevictor/Desktop/学习R/hw1_data.csv'
data = read.csv(direction)
attributes(data)
n_row = nrow(data) # 看有多少行
n_col = ncol(data) # 看有多少列
data[(n_row-1):n_row,] # 这里在slice的时候一定要加括号!!!
data[['Ozone']][47]

num_of_missing_values = is.na(data)
missing = data[num_of_missing_values]
length(missing)

get_mean = data['Ozone']
get_mean = get_mean[!is.na(get_mean)]
mean(get_mean)

extract = data[data['Ozone'] > 31]

$names
[1] "Ozone"   "Solar.R" "Wind"    "Temp"    "Month"   "Day"    

$class
[1] "data.frame"

$row.names
  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150 151 152 153

Ozone Solar.R Wind Temp Month Day
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

[1] 21

[1] 44

[1] 42.12931

In [295]:
extract = data[!data['Ozone'] > 31]
extract
a = data['Ozone'] > 31
b = data['Temp'] > 90
a||b

[1]  12.0  18.0    NA  28.0  23.0  19.0   8.0    NA   7.0  16.0  11.0  14.0
 [13]  18.0  14.0   6.0  30.0  11.0   1.0  11.0   4.0    NA    NA    NA  23.0
 [25]    NA    NA    NA    NA    NA    NA  29.0    NA    NA    NA  23.0    NA
 [37]    NA  21.0  20.0  12.0  13.0    NA    NA    NA    NA    NA    NA    NA
 [49]    NA    NA    NA    NA    NA  10.0  27.0    NA   7.0  16.0    NA    NA
 [61]  20.0   9.0  16.0    NA    NA  28.0    NA  22.0  23.0  31.0  21.0   9.0
 [73]    NA    NA  20.0  23.0  21.0  24.0  21.0  28.0   9.0  13.0  18.0  13.0
 [85]  24.0  16.0  13.0  23.0   7.0  14.0  30.0    NA  14.0  18.0  20.0 149.0
 [97] 313.0    NA    NA 299.0  99.0  19.0    NA    NA 256.0 290.0 274.0  65.0
[109] 334.0  78.0 322.0  44.0   8.0 320.0  25.0    NA    NA    NA  13.0    NA
[121]    NA    NA    NA    NA    NA 127.0    NA    NA    NA 148.0    NA    NA
[133] 191.0  37.0 120.0 137.0    NA    NA    NA    NA    NA    NA    NA    NA
[145]    NA    NA    NA    NA 264.0 175.0    NA  48.0   7.0    NA    NA  81.0
[157]  24.0  77.0    NA    NA 273.0    NA  71.0 115.0 244.0 259.0  36.0    NA
[169]    NA 252.0 220.0 230.0 259.0 259.0 238.0  24.0 112.0 224.0  27.0 238.0
[181] 201.0 238.0  14.0  49.0  20.0 193.0    NA 191.0 131.0 223.0  12.6  11.5
[193]    NA  14.9   8.6  13.8  20.1    NA   6.9   9.7   9.2  10.9  13.2  11.5
[205]  18.4  11.5   9.7   9.7  16.6   9.7    NA    NA    NA  12.0    NA    NA
[217]    NA    NA    NA    NA   9.7    NA    NA    NA   8.0    NA    NA  14.9
[229]   9.2  11.5  10.3    NA    NA    NA    NA    NA    NA    NA    NA    NA
[241]    NA    NA    NA  14.3  14.9    NA  14.3   6.9    NA    NA   8.6  13.8
[253]   7.4    NA    NA  11.5    NA  10.3   7.4  10.9  15.5  14.3    NA    NA
[265]  10.9  10.3  10.9   9.7  15.5   6.3  10.9  11.5  13.8  10.3  10.3   8.0
[277]  12.6   9.2  10.3  16.6   6.9    NA  14.3   8.0  11.5  74.0  62.0    NA
[289]  66.0  65.0  59.0  61.0    NA  74.0  69.0  66.0  68.0  58.0  64.0  57.0
[301]  68.0  62.0  59.0  73.0  61.0    NA    NA    NA  67.0    NA    NA    NA
[313]    NA    NA    NA  82.0    NA    NA    NA  82.0    NA    NA  77.0  65.0
[325]  73.0  76.0    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
[337]    NA    NA  73.0  81.0    NA  80.0  74.0    NA    NA  82.0  81.0  82.0
[349]    NA    NA  82.0    NA  77.0  76.0  78.0  77.0  72.0    NA    NA  80.0
[361]  78.0  75.0  73.0  76.0  77.0  71.0  71.0  67.0  76.0  68.0  82.0  64.0
[373]  71.0  69.0  63.0  70.0    NA  75.0  76.0  68.0   5.0   5.0    NA   5.0
[385]   5.0   5.0   5.0    NA   5.0   5.0   5.0   5.0   5.0   5.0   5.0   5.0
[397]   5.0   5.0   5.0   5.0    NA    NA    NA   5.0    NA    NA    NA    NA
[409]    NA    NA   6.0    NA    NA    NA   6.0    NA    NA   6.0   6.0   6.0
[421]   6.0    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
[433]    NA   7.0   7.0    NA   7.0   7.0    NA    NA   7.0   8.0   8.0    NA
[445]    NA   8.0    NA   8.0   8.0   8.0   8.0   8.0    NA    NA   9.0   9.0
[457]   9.0   9.0   9.0   9.0   9.0   9.0   9.0   9.0   9.0   9.0   9.0   9.0
[469]   9.0   9.0   9.0    NA   9.0   9.0   9.0   3.0   4.0    NA   6.0   7.0
[481]   8.0   9.0    NA  11.0  12.0  13.0  14.0  15.0  16.0  18.0  19.0  20.0
[493]  21.0  22.0  23.0    NA    NA    NA  28.0    NA    NA    NA    NA    NA
[505]    NA   7.0    NA    NA    NA  13.0    NA    NA  16.0  18.0  19.0  20.0
[517]    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
[529]  12.0  13.0    NA  15.0  21.0    NA    NA  26.0   2.0   3.0    NA    NA
[541]  13.0    NA  16.0  18.0  19.0  21.0  22.0    NA    NA   7.0   8.0   9.0
[553]  10.0  12.0  13.0  14.0  15.0  17.0  18.0  19.0  20.0  21.0  22.0  24.0
[565]  25.0  26.0    NA  28.0  29.0  30.0

[1] TRUE

In [298]:
x <- c(1,3, 5)
y <- c(3, 2, 10)
rbind(x,y)

[,1] [,2] [,3]
x 1    3     5  
y 3    2    10